config/routes.rb
Golo::Application.routes.draw do

resources :users
resources :sessions, :only => [:new, :create, :destroy]

match '/login', :to => 'sessions#new'
match 'logout', :to => 'sessions#destroy'
match '/show', :to => 'users#show'
match '/signup', :to => 'users#new'

match '/search', :to => 'pages#search'
match '/about', :to => 'pages#about'
match '/help', :to => 'pages#help'
match '/contact', :to => 'pages#contact'

root :to => "pages#home"

end

app/models/relationship.rb
# == Schema Information
# Schema version: 20101109032746
#
# Table name: relationships
#
#  id          :integer         not null, primary key
#  follower_id :integer
#  followed_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Relationship < ActiveRecord::Base
  attr_accessible :followed_id

  belongs_to :follower, :class_name => "User"
  belongs_to :followed, :class_name => "User"

  validates :follower_id, :presence => true
  validates :followed_id, :presence => true
end

app/models/user.rb
# == Schema Information
# Schema version: 20101101173124
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#

require 'digest' # required for encryption

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name,
                  :email,
                  :city,
                  :password,
                  :password_confirmation

  has_many :relationships, :foreign_key => "follower_id",
                           :dependent => :destroy
  has_many :reverse_relationships, :foreign_key => "followed_id",
                                   :class_name => "Relationship",
                                   :dependent => :destroy
  has_many :following, :through => :relationships, :source => :followed
  has_many :followers, :through => :reverse_relationships, :source => :follower

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  #validates :password, :confirmation => true automatically creates virtual
  #attribute password_confirmation which is checked to be maching the password.
  validates :password,  :presence => true,
                        :confirmation => true,
                        :length => { :within => 10..40 }
  validates :name,      :presence => true,
                        :length => { :maximum => 32 }
  validates :email,     :presence => true,
                        :uniqueness => { :case_sensitive => false },
                        :format => { :with => email_regex }
  validates :city,      :presence => true

  before_save :encrypt_password

  # authentication func, returns user if valid email/pw combination, else nil
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  # Return true if the users's password matches the submitted passowrd
  def has_password?(submitted_password)
    # compare encrypted_password with the encrypted version of
    # submitted password
    encrypted_password == encrypt(submitted_password)
  end

  def following?(followed)
    relationships.find_by_followed_id(followed)
  end

  def follow!(followed)
    relationships.create!(:followed_id => followed.id)
  end

  def unfollow!(followed)
    relationships.find_by_followed_id(followed).destroy
  end

  private

    def encrypt_password
      # create salt only for new user, not when checking if password matches
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(self.password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/models/user_links.rb
class UserLinks < ActiveRecord::Base
  belongs_to :parent_user, :class_name => 'User', :foreign_key => "parent_user_id"
  belongs_to :child_user, :class_name => 'User', :foreign_key => "child_user_id"
  def parent_user
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end

  def search
    @title = "Find People"
    if params[:search]
      @users = User.find_all_by_city(params[:search])
    else
      @users = nil
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Login"
  end

  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "The combination of email/password you submitted is
                          unknown to us."
      @title = "Login"
      render :new
    else
      login user
      redirect_to user
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @title = @user.name
    @friends = @user.followers(@user.id) + @user.following(@user.id)
  end

  def new
    @title = "Sign up"
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      login @user
      redirect_to @user
      flash[:success] = "Welcome to the Track Database"
    else
      @title = "Sign up"
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  #return logo for website
  def logo
    logo = image_tag "logo.png", :alt => "Golo logo",
                                 :class => "round"
  end

  #return titles for pages
  def title
    base_title = "Golo"
    if@title.nil?
    base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    current_user= user
  end

  def current_user= (user)
    @current_user = user
  end

  def current_user
    # ||= assigns user_from_remember_token to @current_user only if
    # @current_user isn't already assigned. Otherwise @current_user
    # is returned directly
    @current_user ||= user_from_remember_token
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    cookies.delete(:remember_token)
    current_user = nil
  end

  private

    def user_from_remember_token
      # * operator extracts arguments from array, e.g. *[a,b] returs a, b
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div id="index">
  <ul class="form">
    <li>
      <label for="username">username</label><input id="username" type="text" />
    </li>
    <li>
      <label for="password">password</label><input id="password" type="password" />
    </li>
  </ul>
  <div id="buttons">
    <%= link_to 'Signup', new_user_path %>
    <%= link_to 'Login', :controller => "home", :action => "you" %>
  </div>
  
</div>
<span style="color:red; left:400px; position:relative; top:-35px;"><strong>Achtung: </strong>Internet Explorer 6 wird nicht unterstützt.</span>

app/views/layouts/_footer.html.erb
<div class="footer">

  <span>&copy; Willytown Connections Inc.</span>
  <%= link_to "About", about_path %>
  <%= link_to "Contact", contact_path%>

</div>

app/views/layouts/_navigation.html.erb
<div class="header">
  <div class = "horizontal">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <% if logged_in? %>
        <li><%= link_to "Profile", user_path(current_user.id) %></li>
        <li><%= link_to "Logout", logout_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Login", login_path %></li>
        <li><%= link_to "Sign up", signup_path%></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_search_by_city.html.erb
<div>
  <%= form_tag search_path, :method => 'get' do %>
    <div class = "field">
      <%= label_tag :search_by_city %>
      <%= text_field_tag :search, params[:search] %>
    </div>
    <div class = "actions">
      <%= submit_tag "Search", :name => nil %>
    </div>
  <% end %>
  <div>
    <% if @users.nil? %>
    <% else %>
      <% @users.each do |user| %>
        <%= link_to user.name, user_path(user.id) %>
        <%# create button for adding user %>
        <%# link_to "User adden", current_user.relationships.create!(:followed_id => user.id) %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
  </head>
  <body>

    <div id="page">
      <div id="navigation">
        <%= render "layouts/navigation" %>
      </div>
      <% flash.each do |key, value| %>
        <div class = "flash <%= key %>" %>
        <%= value %>
        </div>
      <% end %>
      <div id="content">

        <%= yield %>
      </div>

      
        <%= render "layouts/footer" %>
        
      
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<p>written by paul</p>

app/views/pages/contact.html.erb
<p>The contact page</p>

app/views/pages/find.html.erb
<div>
  <%= form_for(@users) do %>
    <div class = "field">
      <%= f.label :city %><br>
      <%= f.text_field :city %>
    </div>
    <div class = "actions">
      <%= f.submit "Search" %>
    </div>
  <% end %>
</div>

app/views/pages/help.html.erb
<p>Sorry, no help available yet</p>

app/views/pages/home.html.erb
<div id="index">
  <div id = "welcome">
    <%= image_tag("logo_1.jpg", :class => "logo") %>
      <%= link_to image_tag("sign_up.png", :alt => "Sign up now", :class => "centered"), signup_path %>
  </div>
  <span><strong>Achtung: </strong>Internet Explorer 6 wird nicht unterstützt.</span>
</div>

app/views/pages/search.html.erb
<div>
  <%= form_tag search_path, :method => 'get' do %>
    <div class = "field">
      <%= text_field_tag :search, params[:search] %><br />
    </div>
    <div class = "actions">
      <%= submit_tag "Search", :name => nil %>
    </div>
  <% end %>
  <div>
    <% if @users.nil? %>
    <% else %>
      <% @users.each do |user| %>
        <%= link_to user.name, user_path(user.id) %>
        <%# create button for adding user %>
        <%# link_to "User adden", current_user.relationships.create!(:followed_id => user.id) %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %><%# puts error or errors%>
      prohibited to save your profile:
    </h2>
    <p>There were problems with the following fields:</p>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<table>
  <% @users.each do |user| %>
    <tr>
      <td> <%= link_to user.name, user_path(user.id)%></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<div class="form">
  <h1>Sign Up</h1>
  <div class = "sign_up">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <div class = "field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class = "field">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
      <div class = "field">
        <%= f.label :city %>
        <%= f.text_field :city %>
      </div>
      <div class = "field">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <div class = "field">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>
      <div class = "submit_150">
        <div class="labelspacer"></div>
        <%= f.submit "Sign up" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div id = "user">
  <h1>
    <%= @user.name %>
  </h1>
  <%#= link_to "Find People", search_path %>
  <%= render 'layouts/search_by_city' %>
  <div id = "sidebar">
    <p>
      <b>buddies</b>
    </p>
    <% @friends.each do |buddy| %>
    <p><%= link_to buddy.name, user_path(buddy.id) %></p>
    <% end %>

  </div>
</div>